title: 이화석<br>Lee <br>Hwaseok
logo: /assets/img/main.jpg
email: ghktjr960@naver.com
description: 목표를 향해 항상 열정적으로 도전하는 마음을 가지고 공부를 이어가고 있습니다!
show_downloads: false
google_analytics: UA-108144808-1
color-scheme: auto
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji
